version: '3'

services:
  adonis-mysql:
    image: mysql:5.7
    ports:
      - '3307:3306'
    volumes:
      - adonis_data_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: adonis
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: tail -f /dev/null
    networks:
      - api-network
  adonis-api:
    container_name: "adonis-api"
    build: .
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - adonis-mysql
    links:
      - adonis-mysql
    networks:
      - api-network
volumes:
  adonis_data_volume:
networks:
  api-network:
    driver: bridge
